#!/usr/bin/env sh

url="$(
  curl -s https://api.github.com/repos/getzola/zola/releases/latest \
    | grep -o 'https://github.com/.*unknown-linux-gnu.tar.gz'
)"

curl -L "$url" -o zola.tar.gz
tar xzf zola.tar.gz

./zola build
